name: Environment 1
variables:
  - name: URL
    value: https://wathiq-back.up.railway.app
    description: ""
  - name: url
    value: http://127.0.0.1:8000
    description: ""
  - name: access_token_admin
    value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3dhdGhpcS1iYWNrLnVwLnJhaWx3YXkuYXBwIiwic3ViIjoiYTc2Njk2NmUtMzVlYi00Y2VjLWIwY2QtODk1MzgzNjgxZjg1IiwiaWF0IjoxNzg5NjUxMTQ0LCJleHAiOjkxNzg5NjUxMTQ0fQ.TabVtySbh81iWPkXXflG68BHqTPpF2RIs1bn8_7-s8A
    description: ""
  - name: access_token_user
    value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3dhdGhpcS1iYWNrLnVwLnJhaWx3YXkuYXBwIiwic3ViIjoiM2Q5YmU1ODItMjkyZC00YzRjLWE1ZWYtNGUyNDlkZDY0OTQ1IiwiaWF0IjoxNzg5NjUxMTYyLCJleHAiOjkxNzg5NjUxMTYyfQ.F1UUKhNKu8u4hOvV2JqTjtMrCC2cM-yMlbMVXPDcXd4
    description: ""
  - name: local_user_token
    value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAiLCJzdWIiOiJjZDczODIzYi1lZTVhLTQxZWMtOTc2ZC1mMzk1NWIwNTdhNTgiLCJpYXQiOjE3ODk5ODMxNjEsImV4cCI6MTA3ODk5ODMxNjF9.8y1aWQ1J4jkStaXfpwTdru24-9y1hnXkxlus9CNnQJI
    description: ""
  - name: lawyer_token_local
    value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAiLCJzdWIiOiJiOGFjODQzMS03ZTlmLTQ0ZWEtODZjMy01MGZhN2I2ZmEwNDciLCJpYXQiOjE3OTAxNjU1MDIsImV4cCI6MTA3OTAxNjU1MDJ9.g20cGeJoVOqq43YSlgMo7hMWaKqYAAdyqaq3XSxg1e8
    description: ""
  - name: admin_token_local
    value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAiLCJzdWIiOiJiNDJkNTc0Mi01MjdlLTQyNTQtYTA5OS01MmQwMWIwMWZlOGQiLCJpYXQiOjE3OTAxNjczMzQsImV4cCI6MTA3OTAxNjczMzR9.cCADe94DFAWb1DA--tfdNVn5J4KL8J2iPUnuCMLz_BU
    description: ""
